### ISSUE TITLE
Bug: buff decimal places

### ISSUE THREAD

**Issue by ShepMC** [MCPrison/Server#104]
https://image.prntscr.com/image/8pOQXqPeSW_KeIuiLWVq1g.png
This shows that there is an insane amount of decimal places, imo it should be rounded or something (the number and the buff) so it is easier for players to understand so maybe in this instance 1.59. Anyway u get the point.

**Comment by HijackingMC** [comment]
@ShepMC The image isn't accessible. http://prntscr.com/nyxpaa

**Comment by ShepMC** [comment]
http://prntscr.com/nyx599
