### ISSUE TITLE
Bug: Autosell upgrading 

### ISSUE THREAD

**Issue by ShepMC** [MCPrison/Server#106]
When you upgrade autosell i dont know if its just me but if you had 64 autosell you dont seem to sell anymore blocks than if you had 1 autosell unless its a very small amount of based on time or something but nothing seems to change much.

**Comment by HijackingMC** [comment]
It does increase:

 Items Sold: x8
 Auto Sell Level: 175

It sells 50% of the backpack @ level 5000, that is selling 0.01% of the backpack each level.

So level 100 = 1% of the backpack, this may seem steep but it is a very OP feature to have, especially combined with pets.

This integrates with the backpack size and such, so if I have a level 5000 item and it holds 100,000 items it'll sell 50,000 every 8 seconds.
