### ISSUE TITLE
Bug/ToDo: Changing Paths

### ISSUE THREAD

**Issue by ShepMC** [MCPrison/Server#110]
When changing your path you lose your talent points that you have on the other path, so my suggestion is to either make it like it used to be so you cant change the path until u spent ur talent points or just add a confirmation menu to change if you have talent points. imo the second one.

**Comment by HijackingMC** [comment]
I tried this not long ago, worked fine?

**Comment by ShepMC** [comment]
Its not that nothing is working but when you change over your path to a different one, if you had any talent points you lose them, im saying there should be a confirmation menu for changing to a different path if u have talent points left to use.

**Comment by HijackingMC** [comment]
Erm, thats not the case?

https://gyazo.com/7e8579328fdb47ec005320408e1c7cd7

0 for Lucky,
3 for Pet,
3 for Buffing (cannot spend as I'm max level)

**Comment by ShepMC** [comment]
Oh do they stay on the actual paths, I understand now, i didnt check for that, just thought they got removed.
