### ISSUE TITLE
Pmine Teleport

### ISSUE THREAD

**Issue by Calille** [MCPrison/Server#12]
When you teleport to you pmine, you get teleported outside of it

**Comment by Serayne92z** [comment]
@HijackingMC I want you to make sure players can set the taxes and open portals in spawn area.

**Comment by ShepMC** [comment]
Could it be done that portals can be set only on certain blocks in spawn, aka the general floor pattern but not the main spawn like dome part or the paths or on the quartz areas. just on the floor pattern parts? I think it would look better imo

**Comment by Calille** [comment]
Make it so that pmines don’t clutter the spawn. On Arkham prison the portals make the spawn look horrible.

I think you should add a feature ‘/pmines’ and this can take you to all of the open pmine portals. The portals can be lined up in a room for players to choose from. I’ll make a test model when I’m available later

**Comment by ShepMC** [comment]
I thought of that too but then doing it on a gui would be just as easy if u want to do it that way, maybe they are automatically enabled and you can disable them being seen via a command or in /settings idk.

**Comment by HijackingMC** [comment]
@Serayne92z,
 What we could do (and is currently a thing) is have it open a menu in spawn, so you can go to an NPC or something similar and open this menu.
 https://gyazo.com/4aa8bdb83dce90eea9aa7aa5f4e4ee10

__Note__
 As tax isn't a thing as of yet, it's not on that menu but can be easily implemented. The state is whether it's open, if its open all people can teleport to it, and if it's closed then only invited members can teleport to it.
