### ISSUE TITLE
Bug: Buycraft NPC’s

### ISSUE THREAD

**Issue by ShepMC** [MCPrison/Server#129]
spoon started off on there with 300+ and every time he buys gift cards it goes down instead of up so like it’s in the 100’s now.

**Comment by Serayne92z** [comment]
That's because the gift cards haven't been spent yet technically?

**Comment by ShepMC** [comment]
Maybe I didn’t explain that clear enough or I’m not getting what your saying but when the npc was introduced spoon was 1st and he has $360 or something. And every time he buys another gift card the amount goes down so even if it was because he hasn’t spent the gift card it shouldn’t go down it should just stay there if that was how it was supposed to be. I am explaining this poorly probably but idk how else to explain it.

**Comment by HijackingMC** [comment]
Issue found,

 The buycraft API returns last recent 100 payments to the store, going to add a manual payment of x amount to furfill the amount spent before x and not drop the database on each purchase, and store amounts etc.
