### ISSUE TITLE
ToDo: Misc bugs Serayne92 finds.

### ISSUE THREAD

**Issue by Serayne92z** [MCPrison/Server#135]
- Monthly Crate should be changed to literally spit out all the items physically outta the ender portal but only the player that used it will actually get anything from it.
- /Help commands should be organized into the categories.

 - Players should be able to type /keys and it brings up a GUI of keys and allows them to submit them into it as a sort of bank by right clicking the key icons and then they can also see how many they have in it and take them out by left clicking the key icons.

**Comment by HijackingMC** [comment]
Currently done:

- Added a confirmation menu when disbanding gang
- Added an op bypass for when using premium features
- Renamed My Cells to My Houses
- Gang scoreboard stuff, a message has been sent to you regarding that
- Sell NPCs with blocks are extremely buggy during my tests of them, bugging out with the npcs and stuff, so they were removed.

**Comment by Serayne92z** [comment]
Be sure to close this after it's done.

**Comment by Serayne92z** [comment]
Merged into other.
