### ISSUE TITLE
Bug: Opening crates

### ISSUE THREAD

**Issue by ShepMC** [MCPrison/Server#163]
When trying to open crates without your pickaxe in your hand you cant unless ur opped. However you can with your pickaxe in your hand.

**Comment by HijackingMC** [comment]
So,
 Bukkit is basically a packet sniffer for Minecraft (Intercepting client packets, then converting them into events etc). If the player has nothing in their hand the client doesn't see a reason to send a packet. This can be overcome in 2 ways.

 We can set the End Portals to some type of chest (So it will interact) or
 We can put up a hologram saying hey, you need to do xxxxx

**Comment by Serayne92z** [comment]
Just use regular chests for crates, there's no reason why all the crates are end portals.

Make the monthly crate an enderchest.
