### ISSUE TITLE
Sheps Dupes & bugs (do not close)

### ISSUE THREAD

**Issue by ShepMC** [MCPrison/Server#173]
Snip - Fixed.

**Comment by ShepMC** [comment]
Will also double check tomorrow if this isn’t dealt with before hand just to see if it is right but p sure it is. Thanks happy

**Comment by ShepMC** [comment]
Bugs:
- No ETPouch in Surfer kit.

**Comment by ShepMC** [comment]
- Quest master said to me “you are able to get new quests, check the questmaster” when i look there its still the same quest just in there.

**Comment by Serayne92z** [comment]
@HijackingMC Done yet?

**Comment by HijackingMC** [comment]
Tested, it regenerated a new quest for me shep.

Also fixing bugs from the previous comments.

**Comment by ShepMC** [comment]
Yes it seems to work now, I dont know wether it was just where i was lagging and checked it so quick.

**Comment by ShepMC** [comment]
https://docs.google.com/document/d/1SMGaNi9Da8uR8TAiNrjBIjf7UIf-kb_sOr7ZB05temY/edit Also this, the titles were never added and monthly crate was never changed nor done. From the way that monthly crate was done the first time it is supposed to have atleast 1 final reward and 1 normal but a couple normal is favoured.

**Comment by ShepMC** [comment]
@HijackingMC some of these are important to be done before release. Others not. If you want me to label the ones that are then I can.

**Comment by HijackingMC** [comment]
@ShepMC I am aware.
