### ISSUE TITLE
Etoken + PToken Dupe Glitch

### ISSUE THREAD

**Issue by Zlexz** [MCPrison/Server#176]
https://www.youtube.com/watch?v=lRITHz_NUmk&feature=youtu.be

**Original dupe**:

Put your omnitool in the crafting proportion and keep it there using Inventory+. Type /newpick

**Patches that were applied for this dupe/other dupes**:

1. Not being able to send commands while in a menu.

2. Not being able to put an omnitool in the crafting proportion.

**How this bypass works**:

Patch 2. is very easily bypassable so I will not be mentioning it from now on.

Normally, if I were to follow the steps from "Original dupe", I wouldn't be able to dupe because of the patches listed above.

One solution would be having the omnitool in the crafting proportion and having the chat spammer type the command. (wouldn't work because of patch #1)

Another solution would be having the omnitool in the crafting proportion, closing the menu you're currently in and typing "/newpick" (this wouldn't work either because it would still say I'm in a menu and wouldn't allow me to type any commands even though I am not).

With these in mind, I started thinking about ways that would allow me to have the omnitool in the crafting proportion without the server not allowing me to type commands (this would involve me not being in a menu and stop the server from not allowing me to send commands, as explained in the precedent paragraph)

I later found out that the solution. Here are the steps you need to follow to replicate this dupe:

1. Enable the "Inventory+" Module from any hacked client;

2. Put the omnitool in the crafting proportion;

3. Exit out of your inventory;

4. Disable the "Inventory+" Module;

5. Click any of the NPCs at spawn that open a GUI (Banker, Casino, Gangs, etc.);

6. Exit out of the GUI that opens;

7. Wait 10 seconds;

8. Type /newpick;

9. Enchant omnitool (This enchants both of the omnitools);

10. Disenchant omnitool  (This only disenchants one of the omnitools);

11. Disenchant  omnitool, again  (This doesn't disenchant anything but still gives you the same amount of tokens)

**Comment by HijackingMC** [comment]
@Zlexz Can you re-check this. I pushed a patch.

**Comment by Zlexz** [comment]
Re-checked. I am still able to put the pickaxe in the crafting proportion after a few tries. @HijackingMC

**Comment by ShepMC** [comment]
I have figured out that randomly if you try it again sometimes the fix works and other times it just gets stuck, no logical order in it either but yeah.
