### ISSUE TITLE
Store Information: Wrong Rewards Listed/Not Working Commands

### ISSUE THREAD

**Issue by DurzoBlints** [MCPrison/Server#180]
On the store the Captain Kit says...

Protection 4 and Unbreakable 3 Armour,
Sharpness 4, Unbreakable 3, Fire Aspect 1 Sword
But instead, in game, I get 
Protection 5 and Unbreakable 3 Armour, 
and Sharpness 5, Unbreakable 3, and Fire Aspect 2 Sword.

In game i also got 32 Golden Apples and 5 Enchanted Golden Apples (rather than 2 listed in the store)

At the moment, it says I can use /warp Surfer but I think it should say /warp Captain. It's like that for all the Ranks, it says that.

I also cannot use the /back, /fix(s) commands and it says I don't have permission to use /invsee though I'm Captain.

**Comment by ShepMC** [comment]
The commands are known but as for everything elseill see if i can get it fixed. Thanks

**Comment by ShepMC** [comment]
The buycraft should be fixed, @HijackingMC can you close this?
