### ISSUE TITLE
Daily Quests [Shard System]

### ISSUE THREAD

**Issue by HijackingMC** [MCPrison/Server#183]
Quest shard well:
This is displayed on a gui at first, however it could also be in spawn. There are different wells, there are Legendary, Epic, Rare & common wells. The well rarity corresponds to the quest rarities above. For example if you complete a legendary quest u get a legendary shard to use in the legendary well.

When opening a well it shows the rewards and their amounts in a holo spinning around the player until they all stop spinning and all remove them selves apart from the one that the player won which would be in front of them. However theres two different rewards guaranteed, etokens and money. Basically there are two of the spinning things which go around one underneath the other one purely for money the other for

Legendary well rewards:

25,000 ETokens 2.5%
22,500 ETokens 7.5%
20,000 ETokens 10%
17,500 ETokens 20%
15,000 ETokens 25%
12,500 ETokens 35%

10B Money 2.5%
7.5B Money 7.5%
5B Money 10%
2.5B Money 20%
1B Money 25%
750M Money 35%

Epic well rewards:

20,000 ETokens 2.5%
17,500 ETokens 7.5%
15,000 ETokens 10%
12,500 ETokens 20%
10,000 ETokens 25%
7,500 ETokens 35%

7.5B Money 2.5%
5B Money 7.5%
2.5B Money 10%
1B Money 20%
750M Money 25%
500M Money 35%

Rare well rewards:

15,000 ETokens 2.5%
12,500 ETokens 7.5%
10,000 ETokens 10%
7,500 ETokens 20%
5,000 ETokens 25%
2,500 ETokens 35%

5B Money 2.5%
2.5B Money 7.5%
1B Money 10%
750M Money 20%
500M Money 25%
250M Money 35%

Common well rewards:

10,000 ETokens 2.5%
7,500 ETokens 7.5%
5,000 ETokens 10%
2,500 ETokens 20%
1,000 ETokens 25%
500 ETokens 35%

2.5B Money 2.5%
1B Money 7.5%
750M Money 10%
500M Money 20%
250M Money 25%
100M Money 35%

**Comment by Serayne92z** [comment]
@HijackingMC Rewards aren't being given, I also don't know where the well is.
