### ISSUE TITLE
Bug: Donor Rank Issues

### ISSUE THREAD

**Issue by IHackedJake** [MCPrison/Server#188]
May be a few things I missed, I just went off of what was listed on buycraft. 

Surfer:

Can only auction 1 item - supposed to be 2
Can view all PVs, but can’t access any

Diver:

Seems to be fine. 

Sailor:

Seems to be fine. 

Captain:

/back isn’t a command - should have it
No perms for /invsee
/fix isn’t a command - should have it
/superchat isn’t a command - should have it

Pirate:

No perms for /donor
Can only auction 1 item, supposed to be 8
No perms for /kitty cannon
No perms for /feed
No perms for /workbench
/supershout isn’t a command - should have it

**Comment by ShepMC** [comment]
@IHackedJake can this be closed if all the info is in the one made further down?

**Comment by IHackedJake** [comment]
Miscommunication - yes, close it.
