### ISSUE TITLE
ToDo: Some Prestige Enchants

### ISSUE THREAD

**Issue by ShepMC** [MCPrison/Server#31]
Tsunami - Extremely low chance to mine out the entire mine. Chance increases per level.
Treasure Hunter - Extremely low chance to find keys while mining. Chance increases per level.

**Comment by Serayne92z** [comment]
Please make sure all prestige enchants have water themed names.

**Comment by ShepMC** [comment]
Ok, i was going off what was on the wiki, which means yeah some need to be changed, lol. Ill try come up with something.

**Comment by Serayne92z** [comment]
Yeah, I realized we fucked up with those enchants when I read this todo, lol.

**Comment by ShepMC** [comment]
Double Trouble (not too sure) - Chance to get multiple etokens when mining. Chance increases per level.
Fishing Funds  - Chance to sell blocks for more extra money. Chance and extra money increases per level.
Reef Shredder - Extremely low chance to mine out the entire mine. Chance increases per level.
Treasure Hunter - Extremely low chance to find keys while mining. Chance increases per level.
Feeding Frenzy (don’t know on this one) - Chance to gain a buff that’ll last for 10 seconds that increases the power of enchants on your pickaxe by 10%. Level this enchant up to increase it's duration and power.

**Comment by ShepMC** [comment]
It’s hard to do it without it sounding rubbish tbh

**Comment by Serayne92z** [comment]
Looks fine to me.

**Comment by Serayne92z** [comment]
Ah, nvm, the old versions were fine.

**Comment by HijackingMC** [comment]
Added all versions,
 Old names have been used.

Any suggestions for new Enchantments / P-Enchantments submit a new issue.
