### ISSUE TITLE
ToDo: Gemstones

### ISSUE THREAD

**Issue by ShepMC** [MCPrison/Server#32]
Players can randomly come across a Gemstone/Gem while mining. Gems come with a random +1 enchantment. These enchantments mimic basic enchantments found in /etshop. This means that you can come across pickaxe and backpack enchantments, but not prestige enchantments. You can combine gemstones together, trade them to other players, or just use them. Gems are a simple and easy way to upgrade pickaxes and backpacks by ignoring all etoken costs.

**Comment by Serayne92z** [comment]
Just want to say that these should be an extremely low chance of dropping, perhaps making it so they're limited to finding one per hour? So they'd find one and then go on a 60 minute cooldown of actual gameplay(Doesn't include afk time) until their next gem.

**Comment by HijackingMC** [comment]
TODO:
 - Make twice as rare as Minecrates.
 - Test.
