### ISSUE TITLE
ToDo: Buff Stations (physical)

### ISSUE THREAD

**Issue by ShepMC** [MCPrison/Server#33]
Next to each prison mine there will be a Buff Station.

**Comment by Serayne92z** [comment]
This should be a simple nice looking area where they unleash their inner super saiyan.

**Comment by ShepMC** [comment]
If wanted i could try create something and danny could bind something, up 2 u.

**Comment by ShepMC** [comment]
Something like this perhaps? https://imgur.com/a/lAHhv4g

**Comment by Serayne92z** [comment]
Yeah, that can work, put some beacons with colored light next to it maybe? Just one behind it?
