### ISSUE TITLE
ToDo: Real Estate / Houses

### ISSUE THREAD

**Issue by ShepMC** [MCPrison/Server#34]
MCPrison has no player plots. Instead, players must earn enough money to afford real estate. Real estate housing can be found all around the prison world. Players can buy these properties to decorate, store items, and make buy/sell shops inside. The interior of every house is fully customizable. Real estate will be available for purchase as soon as server launches, but at very expensive prices. Not only is the upfront cost expensive, but maintaining the property is as well. Every week you must pay real estate taxes to keep your home. Taxes are pre-determined based on the home value. If taxes are not payed, the house will be foreclosed on and put back on the market for purchase.

Type /real estate in-game to open the user interface that shows everything below.

Open houses available
Foreclosed houses available
Option to pay taxes
Option to sell your home
Alternatively, most of these actions can be done by walking up to the physical home in the world and interacting with the owner sign.

**Comment by ShepMC** [comment]
ToDo @HijackingMC:
- Complete player trusted button
- complete player blocked button
- complete house sell button

(adding more when i find it)

**Comment by HijackingMC** [comment]
Complete player trusted button
complete player blocked button
complete house sell button
you seem to be able to buy more than one house which idk if u want but also with that you ony ever see one of your houses in /cells and it only says you own 1 house even known you know you own more.
on /cells it should say there are more houses for sale as they are set up such as house 60 but they arent showing up on their and they are unoccupied.

Fixed.
