### ISSUE TITLE
ToDo: (not to code) Come up with more thought out version of daily quests later on

### ISSUE THREAD

**Issue by ShepMC** [MCPrison/Server#35]
Players will be able to complete up to 5 daily quests each day to earn quest tokens. These tokens can be used for purchasing tax passes (ability to pay your taxes for free), purchasing a house outright, and much more. In order to complete daily quests it will require you to have a discord account linked to your in-game character on our server. Daily quests are IP and discord account locked to prevent the abuse of hoarding quest tokens from alternate accounts.

**Comment by Serayne92z** [comment]
Daily quests shouldn't allow you to purchase a house outright.

I think we should consider removing the daily quest system entirely and releasing a more thought out version of it later on.

**Comment by ShepMC** [comment]
Okay. In which case that part needs removing from the wiki.
