### ISSUE TITLE
ToDo: Login Rewards

### ISSUE THREAD

**Issue by ShepMC** [MCPrison/Server#36]
Players will gain log in rewards for every day in a row they log in. Log in rewards are shown like a calendar in-game and are accessible with the command /login. You have to manually click the correct box/day to check in. Much like daily quests, we require you to have a discord account linked to your in-game character on the server. Log in rewards are also specific to IP. People who abuse our safeguards will be permanently removed from our server. Rewards are not based on the monthly calendar, but instead a calendar that goes for exactly 30 days. Rewards will get progressively better towards the end of the month and very good at 7 day consecutive log in milestones. Weekends will count as checking in twice and will allow you to claim two days of check in instead of one.

**Comment by HijackingMC** [comment]
Started development,
**Update No. 1**
 Added a Menu, got daily rewards, and started database integration.

Todo:
 - Add all of Reward#giveReward parameters
 - Test throughly
 - Add a cooldown to timebuilder to the menu.

Current Revision: https://youtu.be/FLLSzjQrsGA
