### ISSUE TITLE
ToDo: Scoreboard finish

### ISSUE THREAD

**Issue by ShepMC** [MCPrison/Server#42]
Add something on the scoreboard where it says #ToDo under Player (the part that says Placeholder)

**Comment by HijackingMC** [comment]
**NOTE (SELF)**
- Rolling average of average etokens earned -> MONGO INTEGRATION

**Comment by Serayne92z** [comment]
Scoreboard should be only Profile and Path at all times, the other information it cycles to is completely pointless.
