### ISSUE TITLE
ToDo: Crates

### ISSUE THREAD

**Issue by ShepMC** [MCPrison/Server#43]
Finish all crates.

**Comment by HijackingMC** [comment]
TODO:
 - Add misc features of other modules,
 - Finish the giveReward method of current crates
 - Add the rest of them.

**Comment by ShepMC** [comment]
Also whats happening with the /crates GUI

**Comment by HijackingMC** [comment]
Will most likely get removed or depreciated, and replaced with it going to the warp location.

**Comment by HijackingMC** [comment]
Update:
 - Added personal boosters to Vote, Lobster, and Dolphin Crate
 - Added Shark Crate.

**Comment by ShepMC** [comment]
@HijackingMC i think the last thing is depeciate the /crates command.
