### ISSUE TITLE
PVP Region Setup

### ISSUE THREAD

**Issue by HijackingMC** [MCPrison/Server#45]
Todo: 
 - Setup region below spawn
 - Sync across all shards
 - Test

**Comment by ShepMC** [comment]
I have created the region and allowed pvp so things left to do are:
- Auto disable fly
- make it so the lava does not affect them
- Make it so theres no fall damage
- Disable some commands within

**Comment by HijackingMC** [comment]
Done:
 - Added the module to auto toggle flight (will disable if in a pvp zone, will retoggle if not)
 - Changed the barrier system in warp pvp (to work more efficiently)
 - Removed fall damage across the whole server
 - Removed lava damage across the whole server.

__Submit a new PR with commands that should be disabled__
