### ISSUE TITLE
Bug: Pick Loss

### ISSUE THREAD

**Issue by ShepMC** [MCPrison/Server#46]
When you open your inventory which is full and you have your pickaxe in there you can take a block from a stack of blocks and click on the pick so you have the pick in your hand and a full inv and then it can’t return and just disappears. 

If you want me to get a vid I can.

**Comment by HijackingMC** [comment]
Is this creative only?

**Comment by ShepMC** [comment]
Nope it happens in survival too.

**Comment by HijackingMC** [comment]
Can you create a video?

**Comment by ShepMC** [comment]
https://gyazo.com/136fc6c3645437f465874f9d614e515b

**Comment by HijackingMC** [comment]
Bug is currently in testing,
 https://gyazo.com/0b3e3a857bf8bba6e3b75c31dc77e062 (**patched?**)
