### ISSUE TITLE
ToDo: AH Categories

### ISSUE THREAD

**Issue by ShepMC** [MCPrison/Server#48]
Instead of the /ah categories "Armour, Weapons, Enchantments, Food, Materials, Equipment, Spawners and Misc", change them to more prison related ones such as: "Blocks, Buffs, PvP, Misc" etc

**Comment by HijackingMC** [comment]
@ShepMC please do the following:
 - Compile a list of what categories there should be,
 - For each list, compile a list for what should be in each category,

After I have that information I can work on the new category system.
