### ISSUE TITLE
ToDo: Minecrates

### ISSUE THREAD

**Issue by ShepMC** [MCPrison/Server#49]
**Dont know if this is still wanted but @HijackingMC sent it in #ToDo and im moving everything over so it is seen:**
When opening a minecrate, rather than opening an ender chest and taking the item, have the item hover above the minecrate with the reward in a holo, along with a message in chat saying what you got. Also cancel the chest opening

**Comment by HijackingMC** [comment]
Perspective:
 - Holograms would look horrible, and may get in the way of others, if too long.
 - Changed from the chest to a lucky block
 - Players can now click what they want, and gives rewards directly (crates add to virtual crates, etc)
 - A message is sent to the player on what they win, so after winning a few, they'll get used to the icons that are shown in the gui.
