### ISSUE TITLE
ToDo: Gang GUI

### ISSUE THREAD

**Issue by ShepMC** [MCPrison/Server#51]
**Dont know if this is still wanted but Serayne sent it in #ToDo and im moving everything over so it is seen:**
Make a /gang GUI with everything looking like a snacc.

**Comment by Serayne92z** [comment]
Yes, needs to be done.

**Comment by Serayne92z** [comment]
https://docs.google.com/document/d/1smkq_6lE4gI5rJawSYH_1SQNd-enun7JP96EDQnR9mE/edit

This needs to be finished for paths and gangs including all descriptions in the GUI menus and you need to add signature talent information to them.

You also need to make it so it tells them to pick a path by typing /path in game if they do not currently have a path active.

**Comment by ShepMC** [comment]
Also could we perhaps have a command so people can change gang owners? if not then dw but it may help.

**Comment by HijackingMC** [comment]
Will add.
