### ISSUE TITLE
ToDo: Help GUI (encyclopedia)

### ISSUE THREAD

**Issue by ShepMC** [MCPrison/Server#52]
Finish the encyclopedia through the document that you have access to. Please make sure to add everything how it was as I have noticed some things missing.

**Comment by HijackingMC** [comment]
Please reference the documents,

 - Make it **view only**.

**Comment by ShepMC** [comment]
https://docs.google.com/document/d/1AUuufv05zUR9u5HL1HYylDyTdSSu74zMlxA-iwabRAM/edit?usp=sharing
That is the general document.
