### ISSUE TITLE
ToDo: Finish Donor Rank Perms

### ISSUE THREAD

**Issue by ShepMC** [MCPrison/Server#53]
Please finish donor rank perms, I will try to get a list together of what they dont have if I can.

**Comment by HijackingMC** [comment]
Sure,
 Send me a compiled list and I'll get to work.

**Comment by ShepMC** [comment]
Things that need to be added.

**Surfer:**
- Access to surfer kit
- Access to storing stuff in /pv (being worked on alr i believe but ill still put here)
- Make coloured signs

**Diver:**
- Access to surfer mine (unless you dont want them to have access to it)
- Access to Diver kit ( if you want them to have access to the kits below as well then do that too)
- Access to donator channel
- Make coloured signs

**Sailor:**
- Access to /sethome (3 homes)
- /withdraw
- /block
- Access to Sailor kit ( if you want them to have access to the kits below as well then do that too)
- Keep xp on death
- Access to rank mines below this rank (unless you dont want them to have access to it)
- Access to donator channel
- Make coloured signs
- /heal

**Captain:**
- 1.4x sell multi
- Access to /marry
- /sethome (4 homes)
- Access to donator channel
- Keep xp on death
- /gift
- /block
- Some colours on /colour
- /ah 6 items
- /rename everything except picks
- Make coloured signs
- /feed
- /withdraw
- /workbench
- /heal
- /back
- /enderchest
- /fix hand
- /fix all
- /superchat (any chat formatting except for &k)
- /kit Captain (and any other kits below if wanted)
- /hat
- /invsee
- /b

**Pirate:**
- Access to donator channel
- Make coloured signs
- /heal
- /block
- /fix hand
- /fix all
- /withdraw
- /marry
- keep xp on death
- /rename other than pickaxe
- auction 8 items
- /gift
- maybe more colours on /colour idk
- /sethome (4 homes)
- /hat
- /kittycannon
- mine in lower mines if wanted
- /feed
- /workbench
- /back
- /invsee
- /b
- /kit pirate and below if wanted
- /superchat
- /enderchest

**Comment by HijackingMC** [comment]
Done so far:
 - Kits
 - Mines

Will keep updating this slowly.

**Comment by HijackingMC** [comment]
Closed due to a new list being reworked.

__ETA__ tonight or tomorrow.
