### ISSUE TITLE
Idea/ToDo: Hub Auto announcements

### ISSUE THREAD

**Issue by ShepMC** [MCPrison/Server#55]
Set auto announcements in hub different to the ones in valour.

**Comment by Serayne92z** [comment]
You need to tell him what to change them to.

**Comment by HijackingMC** [comment]
Need as stated by Serayne.

**Comment by ShepMC** [comment]
**Do not implement yet danny still working things out**
I have come up with this:
- C.Yellow + "To link your discord type " + C.Green + "/linkdiscord" + C.Yellow + "and follow the steps provided!"
- C.Yellow + "Support us @" + C.Green + "buy.mcprison.com"
- C.Yellow + "Click the " + C.Green + "compass" + C.Yellow + "to start your adventure!"
- C.Yellow + "If you need help, ask a staff member who is on " + C.Green + "/staff"
- C.Yellow +
