### ISSUE TITLE
Suggestion/todo (maybe): Shop NPC's

### ISSUE THREAD

**Issue by ShepMC** [MCPrison/Server#62]
In spawn, there are 4 market stalls. I was thinking you could have an npc for each sub section of /shop and nice skins for them representing the different categories. This is more of a suggestion but yeah.

**Comment by HijackingMC** [comment]
Added 5 NPCs as of yet,
 - PVP
 - Food
 - Banners
 - Decoration
 - Blocks

Will add 5 more on the other side, once the rest of the shop categories are done.
