### ISSUE TITLE
Bug: 1.8 pvp issues

### ISSUE THREAD

**Issue by ShepMC** [MCPrison/Server#63]
So in pvp it seems that the god apples give the non 1.8 effects, the 1.8 effects would be 5 minutes of resistance 1, 5 minutes of fire resistance and 2 absorption hearts (can't remember how long) and regen 5 for 30 seconds
Not sure if W tapping works either, but that could just be cause I'm laggy myself and don't really see it. It's where the player resets their sprint between hits to deal more kb every hit as the first hit of a sprint combo deals the most kb

**Comment by HijackingMC** [comment]
Fixed the golden apples, I don't think anything can be done about the W-Tap, if it is an issue.
