### ISSUE TITLE
Bug: /v Bugs

### ISSUE THREAD

**Issue by ShepMC** [MCPrison/Server#66]
- When you click on npcs in /v it brings up an empty inventory no matter what the npc normally does.
- Npcs still follow you when you are in /v as in they still look at you meaning that players could know that you are there, especially if you are looking for hackers.
- When in /v it still says you are online in /seen.
- Players can pm people in vanish.
- Players can request to marry people in vanish
- Players can see people in vanish's particles (the water drops)
- players can gift things to people in vanish
- Still counts vanished people in the player count (not too much of an issue).

**Comment by HijackingMC** [comment]
Fixed so far:
 - Empty inventory for vanished players on NPCs,
 - NPC looking close at vanished players,
 - Being able to do a seen query to see if they're online,
 - Vanished players still having water particles,
 - Fixed being able to request to marry married players,
 - Fixed being able to message vanished players
 - Fixed being able to gift items to vanished players,

Playercount is an iffy situation, as it would require a performance decrease. I'll look into it in the near future how-ever.
