### ISSUE TITLE
Bug (i think): Coral blocks die

### ISSUE THREAD

**Issue by ShepMC** [MCPrison/Server#81]
Coral blocks die when you break one block in the mine. If this cant be disabled again then what we could do is change it so that coral blocks are worth less. It takes them a bit of time to update across the whole mine so people can still get the more valuable blocks. Or just leave it as normal up 2 u.

**Comment by ShepMC** [comment]
Tested again and the main one is tube coral block that it happens to.

**Comment by HijackingMC** [comment]
Video and block name?
