### ISSUE TITLE
ToDo: Change JH and Explosive description

### ISSUE THREAD

**Issue by ShepMC** [MCPrison/Server#87]
JH and explosive description in /etshop and on the /encyclopedia are wrong at the moment because JH & explo was changed not so long ago.

**Comment by HijackingMC** [comment]
What shall it be changed to?

**Comment by ShepMC** [comment]
https://cdn.discordapp.com/attachments/527844358737756171/581149820215885826/image0.png
These are what it does. However for what to actually write im not too sure. Maybe something like "This gives you a chance to mine somewhere between 20x20 and 40x40." for jackhammer idk.
