### ISSUE TITLE
Mine V not automine

### ISSUE THREAD

**Issue by ShepMC** [MCPrison/Server#9]
Mine V is reportedly not automine cause of the block type whereas others are.

**Comment by HijackingMC** [comment]
Tried, worked fine on 1.13.2,

Could be different on 1.8.

**Comment by ShepMC** [comment]
Sorry it’s mine F my bad, it is wool block if you aren’t in 1.13 apparently

**Comment by HijackingMC** [comment]
Fixed in the protocol patched pushed a few days back,
Changes a lot of blocks to better, respective colours.

F is now **stained clay**.
